### ISSUE TITLE
Typescript compile error - readonly MenuItemConstructorOptions[] error TS1005: ',' expected.

### ISSUE THREAD

**Issue by sachetsharma1** [sindresorhus/electron-util#42]
I am getting an error after upgrading electron-util to 0.14.2 with Electron 11.2.3. Typescript version is 3.3.

node_modules/electron-util/index.d.ts:513:46 - error TS1005: ',' expected.

513 export function appMenu(menuItems?: readonly MenuItemConstructorOptions[]): MenuItemConstructorOptions;

**Comment by sindresorhus** [comment]
You need to upgrade your TypeScript version.
